# Generated by Django 2.1.3 on 2018-11-18 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateTimeField()),
                ('cpf', models.CharField(max_length=11)),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone_fixo', models.CharField(max_length=15)),
                ('telefone_celular', models.CharField(max_length=15)),
                ('e_mail', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
