# Generated by Django 2.1.3 on 2018-11-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
